spring:
  application:
    name: graphql
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  graphql:
    graphiql:
      enabled: true

server:
  port: 8090

app:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'